/****** Script for SelectTopNRows command from SSMS  ******/

/* for testing purposes
IF OBJECT_ID('PecanStreetTestDB.dbo.test_2020', 'U') IS NOT NULL DROP TABLE PecanStreetTestDB.dbo.test_2020;

GO

IF OBJECT_ID('PecanStreetTestDB.dbo.test1_2020', 'U') IS NOT NULL DROP TABLE PecanStreetTestDB.dbo.test1_2020;

GO

IF OBJECT_ID('PecanStreetTestDB.dbo.test2_2020', 'U') IS NOT NULL DROP TABLE PecanStreetTestDB.dbo.test2_2020;

GO

SELECT * INTO [PecanStreetTestDB].[dbo].[test_2020] FROM [PecanStreet].[dbo].[p2020_expanded];

GO
*/

/* 1. Compute gen and store in [PecanStreetTestDB].[dbo].[pYYYY_exp], you must have the data already uploaded ex: [PecanStreet].[dbo].[p2019_expanded]
   2. Compute use, which uses gen + grid
*/


/* Compute gen and store in new table */
SELECT [dataid]
      ,[localminute]
	  ,[air1]
      ,[air2]
      ,[air3]
      ,[airwindowunit1]
      ,[aquarium1]
      ,[bathroom1]
      ,[bathroom2]
      ,[bedroom1]
      ,[bedroom2]
      ,[bedroom3]
      ,[bedroom4]
      ,[bedroom5]
      ,[battery1]
      ,[car1]
      ,[car2]
      ,[circpump1]
      ,[clotheswasher1]
      ,[clotheswasher_dryg1]
      ,[diningroom1]
      ,[diningroom2]
      ,[dishwasher1]
      ,[disposal1]
      ,[drye1]
      ,[dryg1]
      ,[freezer1]
      ,[furnace1]
      ,[furnace2]
      ,[garage1]
      ,[garage2]
	  ,coalesce(solar+solar2+battery1,solar+solar2,solar+battery1,solar2+battery1,solar,solar2,battery1) AS gen
      ,[grid]
      ,[heater1]
      ,[heater2]
      ,[heater3]
      ,[housefan1]
      ,[icemaker1]
      ,[jacuzzi1]
      ,[kitchen1]
      ,[kitchen2]
      ,[kitchenapp1]
      ,[kitchenapp2]
      ,[lights_plugs1]
      ,[lights_plugs2]
      ,[lights_plugs3]
      ,[lights_plugs4]
      ,[lights_plugs5]
      ,[lights_plugs6]
      ,[livingroom1]
      ,[livingroom2]
      ,[microwave1]
      ,[office1]
      ,[outsidelights_plugs1]
      ,[outsidelights_plugs2]
      ,[oven1]
      ,[oven2]
      ,[pool1]
      ,[pool2]
      ,[poollight1]
      ,[poolpump1]
      ,[pump1]
      ,[range1]
      ,[refrigerator1]
      ,[refrigerator2]
      ,[security1]
      ,[sewerpump1]
      ,[shed1]
      ,[solar]
      ,[solar2]
      ,[sprinkler1]
      ,[sumppump1]
      ,[utilityroom1]
      ,[venthood1]
      ,[waterheater1]
      ,[waterheater2]
      ,[wellpump1]
      ,[winecooler1]
      ,[leg1v]
      ,[leg2v]
INTO [PecanStreetTestDB].[dbo].[p2019_exp] FROM [PecanStreet].[dbo].[p2019_expanded];

GO

/* Compute use from gen store in new table */
SELECT [dataid]
      ,[localminute]
	  ,coalesce(gen+grid,gen,grid) AS 'use'
	  ,[air1]
      ,[air2]
      ,[air3]
      ,[airwindowunit1]
      ,[aquarium1]
      ,[bathroom1]
      ,[bathroom2]
      ,[bedroom1]
      ,[bedroom2]
      ,[bedroom3]
      ,[bedroom4]
      ,[bedroom5]
      ,[battery1]
      ,[car1]
      ,[car2]
      ,[circpump1]
      ,[clotheswasher1]
      ,[clotheswasher_dryg1]
      ,[diningroom1]
      ,[diningroom2]
      ,[dishwasher1]
      ,[disposal1]
      ,[drye1]
      ,[dryg1]
      ,[freezer1]
      ,[furnace1]
      ,[furnace2]
      ,[garage1]
      ,[garage2]
	  ,[gen]
	  ,[grid]
      ,[heater1]
      ,[heater2]
      ,[heater3]
      ,[housefan1]
      ,[icemaker1]
      ,[jacuzzi1]
      ,[kitchen1]
      ,[kitchen2]
      ,[kitchenapp1]
      ,[kitchenapp2]
      ,[lights_plugs1]
      ,[lights_plugs2]
      ,[lights_plugs3]
      ,[lights_plugs4]
      ,[lights_plugs5]
      ,[lights_plugs6]
      ,[livingroom1]
      ,[livingroom2]
      ,[microwave1]
      ,[office1]
      ,[outsidelights_plugs1]
      ,[outsidelights_plugs2]
      ,[oven1]
      ,[oven2]
      ,[pool1]
      ,[pool2]
      ,[poollight1]
      ,[poolpump1]
      ,[pump1]
      ,[range1]
      ,[refrigerator1]
      ,[refrigerator2]
      ,[security1]
      ,[sewerpump1]
      ,[shed1]
      ,[solar]
      ,[solar2]
      ,[sprinkler1]
      ,[sumppump1]
      ,[utilityroom1]
      ,[venthood1]
      ,[waterheater1]
      ,[waterheater2]
      ,[wellpump1]
      ,[winecooler1]
      ,[leg1v]
      ,[leg2v]
INTO [PecanStreet].[dbo].[p2019_exp_eng]
FROM [PecanStreetTestDB].[dbo].[p2019_exp];

GO
